---
title: "Thesis_Test_Program"
author: "Joshua Idachaba"
date: "1/1/2022"
output: html_document
---
#Data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Current Working Directory
tryCatch({
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
  }, error=function(cond){message(paste("cannot change working directory"))
})



```



```{r DataPrep}
#Packages Used
library(tensorflow)
library(tidyverse)
library(keras)
library(DataExplorer)
library(haven)
library(e1071)
library(caret)
library(ISLR)
library(recipes)
library(mice)
library(doParallel)
library(pROC)

#Start Parallelization
detectCores() #Check the Number of cores on your computer
num_cores <- 7 #note: you can specify a different number if you want, depending on your preference
cl <- makePSOCKcluster(num_cores)
registerDoParallel(cl)

?mice
mice
#Import Demographics dataset to start
demographics <- read_xpt("DEMO_J.XPT")
diet_behavior <- read_xpt("DBQ_J.XPT")
combined <- demographics %>% left_join(diet_behavior[c(1,40)], by = "SEQN")


#Join all data by SEQN
# for (filename in list.files(".", pattern = "*J.XPT")) {
#   if (filename == "DBQ_J.XPT"){
#     data <- read_xpt(filename)
#     combined <- combined %>% left_join(data, by = "SEQN")
#   }
# }

#Checking which data sets have the SEQN Identifier column
for (filename in list.files(".", pattern = "*J.XPT")) {
   data <- read_xpt(filename)
   print(filename)
   print(length(data %>% select(contains("SEQN"))))
}

#Look at Missing Data
plot_intro(combined)
summary(combined)
```



```{r test}
#MICE Imputation (mice::mice)
a <- Sys.time()
combined_mice <- mice(combined, m = 5, seed = 2022, method = "cart", maxit = 40)
b = Sys.time()
print("MICE")
print(b-a)


#MICE Imputation- Parallel (mice::parlmice)
a <- Sys.time()
combined_mice_parallel <- parlmice(combined, m = 18, seed = 2022, method = "cart", n.core = 7, n.imp.core = 2, cluster.seed = 1995, maxit = 40)
b = Sys.time()
print("Parallel MICE")
print(b-a)

artb <- plot_missing(combined_rev)
ff <- combined_mice$data
#Note: parlmice allows for parallelization of MICE imputations across multiple cores. For more information on parlmice, you may visit https://www.rdocumentation.org/packages/mice/versions/3.13.0/topics/parlmice or https://www.gerkovink.com/parlMICE/Vignette_parlMICE.html


a <- Sys.time()
combined <- mice(combined, m = 1, seed = 2022, method = "cart")
b = Sys.time()
print(b-a)

parl


combined = combined %>% mutate(CBQ596 = ifelse(is.na(CBQ596) | CBQ596 == 9, 2, CBQ596))
combined$CBQ596 = as.factor(combined$CBQ596)


set.seed(1995)
combined_rev <- complete(combined_mice)
combined_rev <- combined_rev %>% select(-c(SDDSRVYR, RIDSTATR, RIDAGEMN)) 
combined <- combined_rev
combined = combined %>% mutate(CBQ596 = ifelse(is.na(CBQ596) | CBQ596 == 9, 2, 1))
combined$CBQ596 <- as.character(combined$CBQ596)
combined <- combined %>% mutate_if(is.character, as.factor)
combined <- combined %>% mutate_if(is.factor, make.names)
combined <- combined %>% mutate_if(is.character, as.factor)
data_index <- createDataPartition(combined[["CBQ596"]], p = 0.7, list = FALSE)
data_train <- combined %>% slice(data_index)
data_test <- combined %>% slice(-data_index)



#KNN
target_var <- 'CBQ596'
model_form <- CBQ596 ~ . 
model_type <- 'knn' # model type 'knn' indicates k-nearest neighbor
positive_class <- 1  # Indicates observations reported seeing MyPlate
negative_class <- 2 # Indicates observations reported not seeing MyPlate

model_recipe <- recipe(model_form, data = data_train) %>% 
  step_novel(all_predictors(), -all_numeric()) %>% # This adds a novel factor level if the test data comes with new levels of a factor
  
  step_unknown(all_predictors(), -all_numeric()) %>% # This assigns a missing value in a factor variable to 'unknown'
  
  step_dummy(all_nominal(), -all_outcomes()) %>% # This creates dummy variables for each factor except the dependent variable
  
  step_zv(all_predictors()) # This removes variables containing only a single value in their domain


trControl <- trainControl(method='cv', number = 10, savePredictions = TRUE, classProbs = TRUE, summaryFunction = twoClassSummary)

a <- Sys.time()
knn_combined = train(model_recipe, data= data_train, method = model_type, trControl = trControl, tuneLength = 10, metric = "ROC")
b <- Sys.time()

knn_combined
rf_combined
svm_combined

#Logistic Regression

target_var <- 'CBQ596'
model_form <- CBQ596 ~ . 
model_type <- 'glm' # model type 'glm' indicates logistic regression
positive_class <- "1"  # Indicates observations reported seeing MyPlate
negative_class <- "2" # Indicates observations reported not seeing MyPlate

model_recipe <- recipe(model_form, data = data_train) %>% 
  step_novel(all_predictors(), -all_numeric()) %>%
  step_unknown(all_predictors(), -all_numeric()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors())

trControl <- trainControl(method='cv', number = 10, savePredictions = TRUE, classProbs = TRUE, summaryFunction = twoClassSummary)
a <- Sys.time()
logReg_combined = train(model_recipe, data= data_train, method = model_type, trControl = trControl, tuneLength = 10, metric = "ROC")
b <- Sys.time()

print(b-a)

logReg_combined
summary(data_train)

#LASSO Regression
target_var <- 'CBQ596'
model_form <- CBQ596 ~ . 
model_type <- 'glmnet' # model type 'glmnet' indicates either Ridge Regression (alpha = 0) or LASSO (alpha = 1)

model_recipe <- recipe(model_form, data = data_train) %>% 
  step_novel(all_predictors(), -all_numeric()) %>%
  step_unknown(all_predictors(), -all_numeric()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_normalize(all_predictors()) %>%
  step_zv(all_predictors())

trControl <- trainControl(method = 'cv', number = 10, savePredictions = TRUE, selectionFunction = 'oneSE', summaryFunction = twoClassSummary, classProbs = TRUE)

tGrid <- expand.grid(alpha = c(1), lambda = 10^seq(1, -2, length = 100))

a <- Sys.time()
lasso_combined <- train(model_recipe, data = data_train, method = model_type, trControl = trControl, tuneGrid = tGrid, metric = "ROC")
b <- Sys.time()

lasso_combined
print(b-a)

#Decision Tree
target_var <- 'CBQ596'
model_form <- CBQ596 ~ . 
model_type <- 'rpart' # model type 'glmnet' indicates either Ridge Regression (alpha = 0) or LASSO (alpha = 1)

trControl <- trainControl(method = 'cv', number = 10, savePredictions = TRUE, classProbs = TRUE, summaryFunction = twoClassSummary)

a <- Sys.time()
decisionTree_combined <- train(model_recipe, data = data_train, method = model_type, trControl = trControl, metric = 'ROC', tuneLength = 10)
b <- Sys.time()

print(b-a)

decisionTree_combined

#Random Forest
set.seed(1995)
combined <- combined_rev
combined = combined %>% mutate(CBQ596 = ifelse(is.na(CBQ596) | CBQ596 == 9, 2, 1))
combined$CBQ596 <- as.character(combined$CBQ596)
combined <- combined %>% mutate_if(is.character, as.factor)
combined <- combined %>% mutate_if(is.factor, make.names)
combined <- combined %>% mutate_if(is.character, as.factor)


class(combined$CBQ596)
unique(combined$CBQ596)
data_index <- createDataPartition(combined[["CBQ596"]], p = 0.7, list = FALSE)
data_train <- combined %>% slice(data_index)
data_test <- combined %>% slice(-data_index)
data_test[[target_var]]

target_var <- 'CBQ596'
model_form <- CBQ596 ~ . 
model_type <- 'rf' # model type 'rf' indicates random forest
positive_class <- "X1"  # Indicates observations reported seeing MyPlate
negative_class <- "X2" # Indicates observations reported not seeing MyPlate

as.factor("2")

model_recipe <- recipe(model_form, data = data_train) %>% 
  step_novel(all_predictors(), -all_numeric()) %>%
  step_unknown(all_predictors(), -all_numeric()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors())

# 10-fold cross validation on the training set 
trControl <- trainControl(method = 'cv', savePredictions = TRUE, classProbs = TRUE, summaryFunction = twoClassSummary)

tGrid <- expand.grid(mtry = c(1:25))

#Perform Random Forest
a <- Sys.time()
rf_combined <- train(model_recipe, data = data_train, method = model_type, trControl = trControl, tGrid = tGrid, metric = 'ROC')
b <- Sys.time()
print(b-a)

summary(rf_combined)
unique(rf_combined_pred)
data_test[[target_var]]

rf_combined_pred <- rf_combined %>% predict(data_test, type = "raw")
confusionMatrix(rf_combined_pred, data_test[[target_var]], positive = positive_class)
class(data_test[[target_var]])

unique(data_test[[target_var]])
unique(rf_combined_pred)

rf_combined_probs <- rf_combined %>% predict(data_test, type = "prob")
rf_combined_roc <- roc(data_test[[target_var]], rf_combined_probs[, positive_class], plot = TRUE, print.auc = TRUE, legacy.axes = TRUE, levels = c(negative_class, positive_class))

#SVM


combined_rev <- complete(combined_mice)
combined_rev <- combined_rev %>% select(-c(SDDSRVYR, RIDSTATR, RIDAGEMN)) 
combined <- combined_rev
data_index <- createDataPartition(combined[["CBQ596"]], p = 0.7, list = FALSE)
data_train <- combined %>% slice(data_index)
data_test <- combined %>% slice(-data_index)

target_var <- 'CBQ596'
model_form <- CBQ596 ~ . 
model_type <- 'svmLinear' # model type 'rf' indicates random forest
positive_class <- "X1"  # Indicates observations reported seeing MyPlate
negative_class <- "X2" # Indicates observations reported not seeing MyPlate

trControl <- trainControl(method = 'cv', savePredictions = TRUE, classProbs = TRUE, summaryFunction = twoClassSummary)

tGrid <- expand.grid(C = c(0.001, 0.01, 0.1, 1,5,10,50))

# note: use standardization when building the model!
model_recipe <- recipe(model_form, data = data_train) %>% 
  step_novel(all_predictors(), -all_numeric()) %>%
  step_unknown(all_predictors(), -all_numeric()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_normalize(all_predictors()) %>%
  step_zv(all_predictors())

a <- Sys.time()
svm_combined <- train(model_recipe, data = data_train, method = model_type, trControl = trControl, tuneGrid = tGrid, metric = 'ROC')
b <- Sys.time()
print(b-a)

svm_combined

#Convolutional Neural Network

stopImplicitCluster()
```


